- CENTER_TARGET_OFF: 32
  CENTER_TARGET_ON: 16
  CURSOR_ENTER_CENTER_TARGET: 80
  CURSOR_ENTER_PERIPHERAL_TARGET:
  - 81
  - 82
  - 83
  - 84
  - 85
  - 86
  - 87
  - 88
  CURSOR_ENTER_CORNER_TARGET:
  - 81
  - 82
  - 83
  - 84
  DELAY_PENALTY: 66
  HOLD_PENALTY: 64
  PAUSE: 254
  PERIPHERAL_TARGET_ON:
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22
  - 23
  - 24
  CORNER_TARGET_ON:
  - 17
  - 18
  - 19
  - 20
  CORNER_TARGET_OFF:
  - 33
  - 34
  - 35
  - 36
  REWARD: 48
  TIMEOUT_PENALTY: 65
  TIME_ZERO: 238
  TRIAL_END: 239
  TRIAL_START: 2
  CURSOR_ENTER_TARGET: 80
  CURSOR_LEAVE_TARGET: 96
  CURSOR_ENTER_TARGET_RAMP_UP: 81
  CURSOR_ENTER_TARGET_RAMP_DOWN: 82
  CURSOR_LEAVE_TARGET_RAMP_UP: 97
  CURSOR_LEAVE_TARGET_RAMP_DOWN: 98
  OTHER_PENALTY: 79
  PAUSE_START: 128
  PAUSE_END: 129